MLT-70 Cleanup and update documentation
NationalLibraryOfNorway/warehouse-logistics-service pull request #51
Opened 2024-11-15 11:21 UTC by MormonJesus69420

Cleanup documentation form code, since some parts of it are incomplete/obsolete/out-of-date. Main focus is on the swagger documentation and readme, however other files should be looked over too

2024-12-16 09:35 UTC, anotheroneofthese requested changes

2024-12-16 09:35 UTC, anotheroneofthese commented on src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/OrderStatusUpdate.kt
I have seen this across the port interfaces - what is the reason/benefit from marking these as functional interfaces? Is this done because they can implicitly throw?

2024-12-16 09:35 UTC, anotheroneofthese commented on .github/workflows/deploy-project.yaml
> +                                #     Set "project.build.finalName --> ${project.artifactId}" in pom.xml to drop the version suffix
Is this tab intentional?

2024-12-16 09:35 UTC, anotheroneofthese commented on .github/workflows/deploy-project.yaml
> +  # This job build a Docker image with relevant tags and labels, and publish it in Harbor
Should be "This job build**s** a Docker image with relevant tags and labels, and publish it **to** Harbor"

2024-12-16 09:35 UTC, anotheroneofthese commented on docker/Dockerfile
> +#     and copy it to the docker folder with "cp target/wls.jar docker/wls.jar"
Is this tab intentional?

2024-12-16 10:28 UTC, MormonJesus69420 commented on src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
> +        description = """Item's category, same category indicates that he items can be stored together without any preservation issues.
Hee hee
![michael-jackson](https://github.com/user-attachments/assets/671b18f2-66b8-4bea-9ac2-cff5bc8381b4)

2024-12-16 10:59 UTC, MormonJesus69420 commented on src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
> +                For example: books, magazines, newspapers, etc. can be stored together without damaging each other.""",
Something along the lines of this?

> For example: books, magazines, newspapers, etc. are of type PAPER, and can be stored together without damaging each other.

2024-12-16 11:19 UTC, anotheroneofthese commented on src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ApiItemPayload.kt
> +                For example: books, magazines, newspapers, etc. can be stored together without damaging each other.""",
That is good :+1:

2024-12-16 12:46 UTC, MormonJesus69420 commented on src/main/kotlin/no/nb/mlt/wls/application/hostapi/item/ItemController.kt
> +                    Item was created in the appropriate storage systems.
Correct! My bad

2024-12-16 12:51 UTC, MormonJesus69420 commented on src/main/kotlin/no/nb/mlt/wls/application/synqapi/synq/SynqBatchMoveItemPayload.kt
> +        description = """Signifies the product is missing, damaged, or otherwise suspect, and it requires manual action from the operator.""",
```suggestion
        description = """Signifies the product is a sussy baka and I saw it vent.""",
```

2024-12-16 12:54 UTC, MormonJesus69420 commented on src/main/kotlin/no/nb/mlt/wls/domain/ports/inbound/OrderStatusUpdate.kt
https://kotlinlang.org/docs/fun-interfaces.html#functional-interfaces-vs-type-aliases

I dunno how much use we will get out of this. I was just getting annoyed by SonarLint constantly nagging me about it, and technically they are functional interfaces so I might as well mark them as such.

2024-12-16 14:04 UTC, anotheroneofthese commented on src/main/kotlin/no/nb/mlt/wls/infrastructure/callbacks/NotificationItemPayload.kt
> +                For example: books, magazines, newspapers, etc. can be stored together without damaging each other.""",
Same comment as before regarding specifying category - missed this in the first review round

2024-12-18 08:39 UTC, anotheroneofthese approved these changes

2024-12-18 08:55 UTC, merged